### ISSUE TITLE
Добавлять в избранное (или в "буду смотреть") из карточки фильма/сериала

### ISSUE THREAD

**Issue by mberman12** [slonopot/kp-msx#12]
Когда в поиске находишь фильм или просто в списке видишь его, нажимаешь на него - открывается "карточка фильма/сериала". Там есть кнопка "Смотреть". Хочется добавить кнопку "В избранное" ("В закладки") и/или "Буду смотреть" ("Смотреть позже"). 

Возможно это дубль #8, просто уточняющий детали

**Comment by slonopot** [comment]
Да, нужно делать управление закладками, папками с закладками, закладками в папках, "я смотрю" для сериалов -- это все подразумевается под работой с закладками. Это все запихается в карточку с контентом

Дубль
