### ISSUE TITLE
Переход к следующей/предыдущей серии в сериале

### ISSUE THREAD

**Issue by mberman12** [slonopot/kp-msx#2]
При просмотре серии сериала добавить кнопки `Next` и `Prev` в панель управления проигрывателя в MSX для быстрого перехода к следующей/предыдущей серии в сериале

**Comment by slonopot** [comment]
Возможно в теории, на практике нужно передавать в плеер текущую серию и список всех серий, чтобы дальше из текущего плеера запускать новый плеер со следующей серией. Никто не знает, чем это может обернуться для самого телевизора, потому что если плеер будет открываться поверх старого, а не вместо старого, то дохлый процессор помрет примерно через 2-3 серии. Сделать скорее реально, но готовое решение с кнопкой лупы слева хоть и требует больше действий, но работает прям щас

**Comment by slonopot** [comment]
Передумал и сделал
