### ISSUE TITLE
Настройка на своем сервере

### ISSUE THREAD

**Issue by kviz781** [slonopot/kp-msx#5]
Не должно ли быть ккакого-то промежуточного действия между этими шагами?

./venv/bin/pip install -r requirements.txt
MONGODB_URL="ссылка на монго" MSX_HOST="http://ваш айпи:1234" nohup ./venv/bin/uvicorn --host 0.0.0.0 --port 1234 api:app &

У меня получапется как-то так..
ubuntu@instanc:~ /kp-msx$ MONGODB_URL="mongodb+srv://логин-пароль/" MSX_HOST="само собой ip:1234" nohup ./venv/bin/uvicorn --host 0.0.0.0 --port 1234 api:app &
[1] 278857
ubuntu@instance:~/kp-msx$ nohup: ignoring input and appending output to 'nohup.out'

**Comment by slonopot** [comment]
Да нет, если вы не пропустили http:// в MSX_HOST, то должно отвечать по `IP:1234`. Понажимайте энтер, если вылетит сразу -- появится сообщение. В `nohup.out` есть логи, можно изучить тоже.

Убить можно через `kill 278857`, найти идентификатор процесса через `ps aux | grep uvicorn`.

**Comment by kviz781** [comment]
Пропустил http:// 
Спасибо, завелось
