### ISSUE TITLE
Сделать сброс привязки устройства/плеера к аккаунта

### ISSUE THREAD

**Issue by mberman12** [slonopot/kp-msx#6]
В случае удаления устройства в аккаунте КП или в других случаях (например для теста реализации https://github.com/slonopot/kp-msx/issues/1 ;) полезно уметь отвязывать плеер, чтобы повторно привязать с новым кодом

варианты реализации:

1) пункт меню «отвязать устройство» - и там явно «забывать» код привязки

2) альтернативно - проверять авторизацию всегда на старте (если код уже есть). Если фейл, то удалять код (отвязывать устройство)

оба варианта после себя выдают диалог новой привязки.

**Comment by slonopot** [comment]
Уже сделано: https://github.com/slonopot/kp-msx/commit/dbf3fdb5260c55300dba003af8107204f2a59abc
После отвязки в лк при следующем запуске устройство удаляется из базы и запрашивается повторная авторизация
